### ISSUE TITLE
command_pyroscope.cc has compile error  on rtorrent 0.9.4

### ISSUE THREAD

**Issue by colinhd8** [pyroscope/rtorrent-ps#1]
when i patch&compile against with rtorrent 0.9.2，everything is ok. when update to rtorrent 0.9.4(update to the latest source from the github), then the follow error occured:
command_pyroscope.cc:49:22: error: ‘tr1’ has not been declared
     #define _cxxstd_ tr1
                      ^

**Comment by pyroscope** [comment]
0.9.4 + Wheezy and Trusty work, and with a pre-release compiler you're on your own. Also, no further feedback for ½ a year.
