### ISSUE TITLE
Add 0.9.5 to build

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/rtorrent-ps#10]
https://github.com/rakshasa/rtorrent/releases/tag/0.9.5

**Comment by chros73** [comment]
Does this tag include any important changes at all?
I went quickly through the changeset (though I'm not a C++ programmer), but apart from couple of small mods, it's basicly about compiling.

**Comment by chros73** [comment]
Have you seen that the 0.9.5 tag was removed from the rtorrent/libtorrent repo? :)
https://github.com/rakshasa/rtorrent/issues/322
So, can you compile an official v0.9.4 trusty package with the latest patches included and upload it to bintray?
Thank you!
