### ISSUE TITLE
"Could not compile XMLRPC-C test" on Raspberry Pi.

### ISSUE THREAD

**Issue by meeeo** [pyroscope/rtorrent-ps#104]
Hello.
I tried to install rtorrent-ps on a Raspberry Pi model B (running DietPi - a variation of Raspbian) . 
I followed [this installation guide](http://rtorrent-ps.readthedocs.io/en/latest/install.html#debianinstallfromsource).
At First I encountered the "Could not compile XMLRPC-C test" error, and I noticed that there's a section of code for to resolve that problem in build.sh but I don't know why it didn't work, and after some searchings, I tried to run that build.sh command with "--disable-instrumentation" explicitly, see the screenshot below. But still the same. 
What am I supposed to do? 
Thanks.

<img width="1440" alt="2018-06-27 11 15 53" src="https://user-images.githubusercontent.com/5188710/41951864-a48c4760-79ff-11e8-984f-c54f18f46217.png">

**Comment by meeeo** [comment]
Thank you.
I tried again to put env vars before the command.
<img width="1440" alt="2018-06-27 15 48 49" src="https://user-images.githubusercontent.com/5188710/41961035-ea6f9650-7a23-11e8-84fe-6aa076f02fd9.png">
Still the same.
Here's the config.log.
https://drive.google.com/uc?id=1FyzqcFRMOYBx5diRSghJTb-3zt8p-j5a&export=download

**Comment by pyroscope** [comment]
That log is useless, since it is the one from the succeeding xmlrpc build. What fails is USING xmlrpc.

**Comment by meeeo** [comment]
Thank you.
Succeeding build but fails using it? But why it says that "Could not compile XMLRPC-C" error message, I was sure that's the log file generated by the interrupted building on the screenshot, but now I'm confused. Should I clean_all and do it again and collect that log.

**Comment by pyroscope** [comment]
**rtorrent** uses xmlrpc-c. Come to IRC if you want to continue this, it gets tedious.

**Comment by meeeo** [comment]
Thank you for you patience and sorry for my ignorance.
I just did it again and I noticed that the config.log exited with result 0 means xmlrpc build successfully.
But the building still failed.
<img width="720" alt="2018-06-28 02 51 57" src="https://user-images.githubusercontent.com/5188710/41994444-03af15de-7a81-11e8-9638-68474ee97b36.png">

I'll go to IRC room later, thank you again.

**Comment by pyroscope** [comment]
Closing as dupe oif #76
