### ISSUE TITLE
Color misalignment when Download goes over 999.9 KB

### ISSUE THREAD

**Issue by AshenDrops** [pyroscope/rtorrent-ps#11]
![Image](https://ptpb.pw/GdG5.png)

Shown in the DanganRonpa download

**Comment by chros73** [comment]
It's a known issue. Pyroscope has replied to the very same question here:
https://groups.google.com/forum/#!topic/pyroscope-users/tUIg9sh_6wU

As he suggested, just use the collapsed mode ('*' key), if you have his additional config file.
That view is simply amazing! You can see every important information on it!
A well planned, organized view. Thank you for it, Pyroscope.

**Comment by AshenDrops** [comment]
The collapsed mode is unfortunately too small for my font size. That and
I prefer the readability of the normal mode. Thanks for the input,
though!

**Comment by pyroscope** [comment]
Closed with a1efbf7
