### ISSUE TITLE
Busted master build

### ISSUE THREAD

**Issue by KyleSanderson** [pyroscope/rtorrent-ps#115]
window_download_list.cc: In member function ‘virtual void display::WindowDownloadList::redraw()’:
window_download_list.cc:121:68: error: ‘pos’ was not declared in this scope
     ui_pyroscope_download_list_redraw_item(this, m_canvas, m_view, pos, range);

**Comment by pyroscope** [comment]
zero info about context, what do you expect now?

**Comment by pyroscope** [comment]
stale and no reaction
