### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by exexex** [pyroscope/rtorrent-ps#12]
config.status: executing default-1 commands
configure: ==>
configure: ==>We are not building any client XML transport (see earlier messages explaining why), therefore WE WILL NOT BUILD THE CLIENT LIBRARY.
configure: ==>
rm -f shell_config
Lots of echoes to 'shell_config' suppressed here ...
rm -f xmlrpc-c-config
Echoes to 'xmlrpc-c-config' suppressed here ...
cat shell_config >>xmlrpc-c-config
cat xmlrpc-c-config.main >>xmlrpc-c-config
chmod a+rx xmlrpc-c-config
rm -f xmlrpc-c-config.test
Echoes to 'xmlrpc-c-config.test' suppressed here ...
cat shell_config >>xmlrpc-c-config.test
cat xmlrpc-c-config.test.main >>xmlrpc-c-config.test
chmod a+rx xmlrpc-c-config.test
make -C include/ -f /home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366//include/Makefile \
    all 
make[1]: Entering directory '/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/include'
>xmlrpc-c/config.h
Lots of echoes to 'xmlrpc-c/config.h' suppressed here ...
make[1]: Leaving directory '/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/include'
make -C lib/ -f /home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366//lib/Makefile \
    all 
make[1]: Entering directory '/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/lib'
make -C util/ -f /home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/lib/util/Makefile \
    all 
make[2]: Entering directory '/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/lib/util'
/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/lib/util/Makefile:60: depend.mk: No such file or directory
cat /dev/null >depend.mk
ln -s /home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366 srcdir
ln: failed to create symbolic link ‘srcdir’: File exists
/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/common.mk:313: recipe for target 'srcdir' failed
make[2]: *** [srcdir] Error 1
make[2]: Leaving directory '/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/lib/util'
/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/common.mk:323: recipe for target 'util/all' failed
make[1]: *** [util/all] Error 2
make[1]: Leaving directory '/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/lib'
/home/*/src/rtorrent-ps/xmlrpc-c-advanced-2366/common.mk:323: recipe for target 'lib/all' failed
make: *** [lib/all] Error 2

Linux version 3.19.0-22-generic (buildd@allspice) (gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) ) #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015
Ubuntu 15.04

**Comment by pyroscope** [comment]
Try again, after a `./build-sh clean_all`.

**Comment by exexex** [comment]
that did it, ty
