### ISSUE TITLE
Deleting files, or make large changes makes ruTorrent/rTorrent time out

### ISSUE THREAD

**Issue by enoch85** [pyroscope/rtorrent-ps#122]
I'm using a docker image which are using rtorrent-ps. Before the change (like a few weeks ago) everything was smooth (rtorrent 0.9.7) but since the change, I started to get timeouts in the ruTorrent GUI quite frequently. It typically happens when:

 - I delete a torrent (and data) that holds a few GB of data.
 - I delete multiple torrents at once
 - I add several torrents at once

It's just like it's trying to catch up, and timeouts for a long period of time, and then comes back by itself. I use RSS as well with a 10 minute interval, maybe worth mentioning.

Worth mentioning is that this runs on a VM with 8 vCPUs and 12 GB vRAM. 

Are there any setting, or anything I can do myself to speed things up?

Posting here as per recommended in https://github.com/binhex/arch-rtorrentvpn/issues/121

**Comment by pyroscope** [comment]
Not a rt-ps problem, and likely not even an upstream problem.

If you call commands in your config, you have to handle concurrency, and possibly put stuff in the background. The proper place for config support is Gitter, IRC, or reddit.
