### ISSUE TITLE
Read past initial payload after incoming encrypted handshake.

### ISSUE THREAD

**Issue by carldibert** [pyroscope/rtorrent-ps#128]
While using rtorrent-ps with the most up to date release as of the time that I am posting this I am getting fatal errors that causes rtorrent to crash every 2 hours or so. I have since switched to using vanilla rtorrent 0.9.8/0.13.8 and have been running without a single crash for over 48 hours. It seems as if there has been a fix with libtorrent. When would the timeline be for updating the base of rtorrent or possibly to just patch out this error?

`Caught internal_error: 'Read past initial payload after incoming encrypted handshake.'.
---DUMP---
/usr/lib/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x25a) [0x7f4b7483789a]

/usr/bin/rtorrent(_ZN7torrent14internal_errorC1EPKc+0xb1) [0x55a29d94adb1]
/usr/lib/libtorrent.so.19(+0x3cfe2) [0x7f4b7482cfe2]
/usr/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0xca) [0x7f4b7485291a]
/usr/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x79) [0x7f4b74852a39]
/usr/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x123) [0x7f4b74883583]
/usr/bin/rtorrent(+0x4542c) [0x55a29d8ed42c]
/usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7f4b7440b002]
/usr/bin/rtorrent(+0x45c6e) [0x55a29d8edc6e]`

edit: formatting of error

**Comment by pyroscope** [comment]
That is an upstream problem.
