### ISSUE TITLE
Feature request for Home and End keys on the interface

### ISSUE THREAD

**Issue by chros73** [pyroscope/rtorrent-ps#13]
Can you add support for Home and End keys on the interface:
- home: jump to the top (no torrents selected)
- end: jump to the bottom (last torrent will be selected)

It's pretty annoying to go through for 400-500 torrents if you are in the middle of a view.
Thanks

**Comment by pyroscope** [comment]
```
branch=pyro.extended=,"schedule = bind_home,0,0,\"ui.bind_key=download_list,0406,ui.focus.home=\""
branch=pyro.extended=,"schedule = bind_end, 0,0,\"ui.bind_key=download_list,0550,ui.focus.end=\""
branch=pyro.extended=,"schedule = bind_pgup,0,0,\"ui.bind_key=download_list,0523,ui.focus.pgup=\""
branch=pyro.extended=,"schedule = bind_pgdn,0,0,\"ui.bind_key=download_list,0522,ui.focus.pgdn=\""
```

`ui.focus.page_size` sets the number of items to skip on pgdn / pgup.

**Comment by chros73** [comment]
Wow, that was quick, Thank You! :)

All is working except for the ui.focus.page_size . No matter whether I set it in the config or through CTRL+X, it uses the default (50). e.g.:
ui.focus.page_size=20
ui.focus.page_size = "20"

**Comment by pyroscope** [comment]
Like with all other values, you need *.set=

**Comment by chros73** [comment]
:) I'm so sorry, it's my bad.
