### ISSUE TITLE
bintray binaries unavailable

### ISSUE THREAD

**Issue by imTHAI** [pyroscope/rtorrent-ps#138]
Hello,

I believe you'r not aware but it looks like the website bintray.com has changed.
I tried to retrieve here https://bintray.com/artifact/download/pyroscope as the doc says but I cannot. Is there a mirror somewhere ?

Thank you

**Comment by pyroscope** [comment]
Binaries are github releases by now. Where in the docs?

**Comment by imTHAI** [comment]
After 1,5y I moved on.
Why do you suddenly mind after so long ?

It's on your own doc, and there is a search engine.
![image](https://user-images.githubusercontent.com/36070606/224533803-a52f8fbb-b9ee-4961-8331-6e2aaba5553e.png)

![image](https://user-images.githubusercontent.com/36070606/224533821-4741a033-8f72-4e28-a4c9-f9131f25b986.png)
