### ISSUE TITLE
Issues displaying condensed lines on wheezy

### ISSUE THREAD

**Issue by guyzmo** [pyroscope/rtorrent-ps#20]
Hello,

I have compiled and installed rtorrent-0.9.6 on my Debian Wheezy and when I hit the `*` key, the condensed format look like the following:

       M-b~XM-" M-b~X~M M-b~L~X M-b~\M-0 M-bM-#M-? M-b~ZM-! M-b~XM-/ M-b~Z~Q  M-b~FM-:  M-bM-$M-4  M-bM-$M-5   M-b~H~F   M-b~L~Z M-b~I~@M-b~H~G   M-b~\~G   Name                            Tracker Domain

instead of:

       ☢ ☍ ⌘ ✰ ⣿ ⚡ ☯ ⚑  ↺  ⤴  ⤵   ∆   ⌚ ≀∇   ✇   Name                                                                                                                                       Tracker Domain

I have compiled the exact same way a while back rtorrent-0.9.2 on a debian squeeze, and it was working perfectly fine. The overall configuration of the server's terminal is the same as much as I can tell. I connect to both servers through ssh, using OSX' terminal, I'm using on both zsh. The only difference is one is squeeze and the other one is wheezy.

Here's a screenshot of the issue:

<img width="911" alt="rtorrent-ps-sshot" src="https://cloud.githubusercontent.com/assets/254441/12003225/c51f68ac-ab1e-11e5-86b7-6aba0cf68806.png">

Any idea of what could be causing the issue?

**Comment by pyroscope** [comment]
Use the BinTray DEB for Wheezy.

**Comment by guyzmo** [comment]
I wish I could, but I'm on a 32bits wheezy, and the only arch available is for amd64 on the bintray :-/

**Comment by chros73** [comment]
It looks like you don't have proper locale support in the OS. (I've got similar funky results on OpenWRT a long time ago.)
1. have you installed all the necessary packages first?
2. did you use the build.sh script?

**Comment by guyzmo** [comment]
1. I believe I have, but I might have forgotten something not mandatory
2. yes I did

**Comment by chros73** [comment]
Hhmmm.. Try it out 1 more time: https://code.google.com/p/pyroscope/wiki/DebianInstallFromSource#Preparatory_steps
If it still didn't work, I believe I have a 32bit Wheezy in virtual host, I can try to compile it for you.

**Comment by guyzmo** [comment]
I was missing `libncursesw5-dev` but sadly it did not help… It's really bugging me, in part because it's not working properly, but in part because I don't understand…

**Comment by guyzmo** [comment]
I'd appreciate if you could build it on your system and check whether it's actually working fine for you. That way I'd be able to check whether this is an issue with the compilation or the environment I'm running it on.

**Comment by pyroscope** [comment]
Run this command

    locale -a | grep -i en_US.utf8

If it comes up empty, create the missing locale.

**Comment by guyzmo** [comment]
already went through that, I even ran `locale-gen` and `dpkg-reconfigure locales` :-/

Though when compiling, I'm still getting locale errors with perl…

**Comment by guyzmo** [comment]
finally managed to make it work… 

I made sure to get rid of all locale issues, and ran the compilation on a fresh shell (not within screen), did the compilation and it's working. I'd need to restart my screen session though now.

Thank you for the pointers!
