### ISSUE TITLE
Installation process on OS X

### ISSUE THREAD

**Issue by pulgalipe** [pyroscope/rtorrent-ps#21]
I was trying to install it on Mac OS X, but I don't know where to start.
I can download the source and compile, but don't know how to apply the patches and generate a working binary.
If it had a Homebrew recipe it will be much better, which will benefit all Mac users.
Or at least the README would be updated with instructions to install it.
Thanks for this great project.

**Comment by luxus** [comment]
i tried to build ... first i had some trouble with libtoolize and was just naiv and symlink glibtoolize to it ..
then i got this error when i try to build from github source.
```
In file included from formdata.c:39:
../lib/strequal.h:33:8: error: expected parameter declarator
size_t strlcat(char *dst, const char *src, size_t siz);
       ^
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro
      '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
In file included from formdata.c:39:
../lib/strequal.h:33:8: error: expected ')'
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro
      '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
../lib/strequal.h:33:8: note: to match this '('
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:53: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                    ^
In file included from formdata.c:39:
../lib/strequal.h:33:8: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
size_t strlcat(char *dst, const char *src, size_t siz);
       ^
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:31: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                              ^
In file included from formdata.c:39:
../lib/strequal.h:33:8: error: conflicting types for '__builtin___strlcat_chk'
/usr/include/secure/_string.h:111:3: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
  ^
../lib/strequal.h:33:8: note: '__builtin___strlcat_chk' is a builtin with type
      'unsigned long (char *, const char *, unsigned long, unsigned long)'
/usr/include/secure/_string.h:111:3: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
  ^
1 warning and 3 errors generated.
make[2]: *** [formdata.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1```

**Comment by pulgalipe** [comment]
Try to install liibtool on terminal using:

`curl -OL http://ftpmirror.gnu.org/libtool/libtool-2.4.2.tar.gz
tar -xzf libtool-2.4.2.tar.gz
cd libtool-2.4.2
./configure && make && sudo make install`

Can you post the way you applied patches, 'cause I didn't found it.

**Comment by luxus** [comment]
i installed libtoolize with brew.. 
but still i got the same error message.. it looks like OS X don't like the usage of strlcat

**Comment by chros73** [comment]
I have tried out today, but I got your result, luxus.
Pyroscope added dependency packages into build.sh , so I uncommented it:
`BUILD_PKG_DEPS=( libncurses5-dev libncursesw5-dev libsigc++-2.0-dev libssl-dev libcppunit-dev locales )`

I'm pretty sure these dev packages are missing, but I couldn't find the corresponding packages in Homebrew. I tried after installing these (and received the same error like you):
```
brew install libtool
brew install ncurses
brew link --force ncurses
brew install libsigc++
brew install cppunit
```

**Comment by pyroscope** [comment]
This is a *curl* problem! Also see https://github.com/sleuthkit/sleuthkit/issues/260 for a solution. Try a newer curl, and/or try to compile upstream curl and open a PR *there* if they still have that problem.

**Comment by pyroscope** [comment]
See 58c3111eb7264a08cf5308b7a370855c50cb000a

**Comment by luxus** [comment]
puh, my skills are too low to understand what i can try now :(

**Comment by pyroscope** [comment]
A `git pull --ff-only` and starting a new build. The default curl is now from this month, and xmlrpc-c from October.

**Comment by luxus** [comment]
Thanks for answering, would it be possible to use glibtool and glibtoolize on OS X systems(brew). They just use a different name to prevent conflicts with the builtin libtool

**Comment by luxus** [comment]
thanks for adding the glibtoolize support..

now i end up with this error

```
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/kai/github/rtorrent-ps/libtorrent-0.13.6/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
Making all in src
Making all in torrent
Making all in data
/bin/sh ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../..  -I. -I./.. -I./../.. -I../../.. -I /Users/kai/lib/rtorrent-0.9.6/include  -I/usr/include -I/usr/include  -D_THREAD_SAFE  -O2 -Wall -g -DDEBUG -fvisibility=hidden -I/usr/local/Cellar/openssl/1.0.2f/include -MT block.lo -MD -MP -MF .deps/block.Tpo -c -o block.lo block.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I. -I./.. -I./../.. -I../../.. -I /Users/kai/lib/rtorrent-0.9.6/include -I/usr/include -I/usr/include -D_THREAD_SAFE -O2 -Wall -g -DDEBUG -fvisibility=hidden -I/usr/local/Cellar/openssl/1.0.2f/include -MT block.lo -MD -MP -MF .deps/block.Tpo -c block.cc  -fno-common -DPIC -o .libs/block.o
In file included from block.cc:44:
In file included from ./../../protocol/peer_connection_base.h:42:
./../../torrent/poll.h:40:10: fatal error: 'tr1/functional' file not found
#include <tr1/functional>
         ^
1 error generated.
make[4]: *** [block.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by pyroscope** [comment]
See the issue's label, someone actually on that platform has to make the necessary changes.

**Comment by tzudot** [comment]
@luxus what was suggested in issue https://github.com/rakshasa/libtorrent/issues/47#issuecomment-29075195 did not work for me either. Homebrew formulas, `libtorrent` and `rtorrent` have a hint on how to proceed with the build itself; append `-stdlib=libstdc++` to `CXXFLAGS` before you run `./configure`.
If you want `xmlrpc-c` feature as well, then compile it with the above option.

@pyroscope if you could host a `Homebrew` tap, e.g., `https://github.com/pyroscope/homebrew-rtorrent-ps` under your organization for Mac OS X users, I'm willing to contribute for preparing working formulas for all three packages - `libtorrent`, `xmlrpc-c` and `rtorrent`.

**Comment by luxus** [comment]
@tzudot was you able to build it?

**Comment by tzudot** [comment]
@luxus yes, use the aforementioned build flag option before you run `./configure`.

**Comment by tzudot** [comment]
@pyroscope I'll start a `Homebrew` tap, prepare the formulas, and when they are ready you could host under `pyroscope` organization.

**Comment by luxus** [comment]
@tzudot thanks for your help.
i was able to build when exporting your recommendation before execute build.sh .
but i run into trouble with the old curl version from OS X. i think i will just wait until you release your tap

**Comment by pyroscope** [comment]
Carry on in https://github.com/pyroscope/homebrew-rtorrent-ps/issues

**Comment by pyroscope** [comment]
@tzudot It'd make sense for you to join the freenode IRC channel.

**Comment by luxus** [comment]
hey @tzudot do you have time for this?
greetings from germany

**Comment by tzudot** [comment]
@luxus I apologize for the delay. Could not get online with my irc nick, which I have now sorted out and prior to that went out of station for a bit more than a week.

I have tried to port the install script to Homebrew partially but faced few issues, which I needed discuss on irc.

**Comment by luxus** [comment]
@tzudot did you read the comment on your issue on rtorrent? that you should use head instead of release (0.9.6)

**Comment by flomazter** [comment]
Hello all! I don't understand, how i can install rtorrent-ps on my mac? I try compile this via git, its not working, have an error. And i don't understand how use homebrew tap and add repo there.

**Comment by luxus** [comment]
@flomazter at the moment rtorrent is not working on el capitan with xmlrpc-c 
@tzudot posted the issue here https://github.com/rakshasa/rtorrent/issues/400#issuecomment-200724163
