### ISSUE TITLE
adding makeflags

### ISSUE THREAD

**Issue by tombs007** [pyroscope/rtorrent-ps#22]
I have been trying compile rtorrent-ps with on my arm based dev boards with icecc. No matter what techniques I try the build fails when passing -j<some number>. Is it possible to acheive this

**Comment by pyroscope** [comment]
"passing" to what? achieve what? be more verbose.

**Comment by tombs007** [comment]
I have setup a small cluster of arm based boards for compiling rtorrent-ps. I have tested my setup by compiling nginx from source and the tasks are distributed over the cluster. I added the code to the build.sh to setup the compiler. Steps taken from here: [https://savago.wordpress.com/2012/11/23/icecc-setup-how-to/](url).

When I call ./build.sh I receive failures like this:

Illegal option -j
You don't have the '-j6' command available, you likely need to:
    sudo apt-get install -j6

I have tried export MAKEFLAGS= but does not work.

**Comment by pyroscope** [comment]
There already is a MAKE variable that you can append to, you just have to do it right.

**Comment by tombs007** [comment]
Do you have a recommendation as to how to do it right? As I am unable to resolve it myself.

I have tried:
export MAKE="make -j6"

export MAKEFLAGS="-j6"
export MAKE="make $MAKEFLAGS"

alias make="make -j6"

all result in:
Illegal option -j
You don't have the '-j6' command available, you likely need to:
sudo apt-get install -j6

**Comment by pyroscope** [comment]
You need to read up on bash debugging, specifically set -x.

**Comment by tombs007** [comment]
Will check it out, thanks.
