### ISSUE TITLE
system.method.set_key equivalent?

### ISSUE THREAD

**Issue by s0nspark** [pyroscope/rtorrent-ps#23]
I was using the following in my vanilla rtorrent config to move downloads from a temp dir to a completed dir. 

```
system.method.set_key = event.download.finished,move_complete,"d.set_directory=~/Downloads/;execute=mv,-n,$d.get_base_path=,~/Downloads/"
```

This does not seem to work with the pyro patched version. Is there some equivalent I should be using instead? Also is there documentation of the new config file format somewhere?

**Comment by chros73** [comment]
Try out with `method.set_key` instead.
About documentation: you have to look in the source code of rtorrent. :)

**Comment by chros73** [comment]
And also you can take a look at my setup here: https://github.com/chros73/rtorrent-ps
(It includes all the necessary config, like tmux, init script, putty on Windows, etc.)

**Comment by s0nspark** [comment]
Awesome - thanks so much! :)

**Comment by pyroscope** [comment]
You also changed the rt version, which was the actual trigger for the problem.
