### ISSUE TITLE
Move old wiki pages

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/rtorrent-ps#24]
Move relevant wiki `*.md` files to here, and fix links to them.
- https://github.com/pyroscope/pyroscope/blob/wiki/RtorrentExtended.md
- https://github.com/pyroscope/pyroscope/blob/wiki/RtorrentExtendedCanvas.md
- https://github.com/pyroscope/pyroscope/blob/wiki/DebianInstallFromSource.md
- more?

**Comment by chros73** [comment]
I have found an easy approach (setup 5 mins, maintaining 10 sec :) , also works with branches) to integrate github wiki pages into your project: https://github.com/chros73/rtorrent-ps_setup/issues/82

If you are interested then comment either this or the above ticket.

**Comment by pyroscope** [comment]
Finally done.

**Comment by chros73** [comment]
Good job! :)
