### ISSUE TITLE
Modify rpath-linking to use relative path

### ISSUE THREAD

**Issue by chros73** [pyroscope/rtorrent-ps#31]
Is that possible? It would be a great improvement.
Right now, if I move a compiled dir into another one rtorrent won't work.
I tried myself but I failed in a pretty bad way :)

If it's manageable then modify symlinks as well to use relative path.

**Comment by pyroscope** [comment]
Why would you even need to move stuff around constantly? Just compile for the target location.

**Comment by chros73** [comment]
"constantly" :D 
I don't want to do it all the time, but when I want to try out something it'd be easier if it was relatively linked.
The first question is: is it possible at all?
Thanks

**Comment by pyroscope** [comment]
I don't know. There is easier ways to switch around stuff, like the symlink in ~/bin.

**Comment by chros73** [comment]
No worries, thanks for thinking with me.
