### ISSUE TITLE
Config error with latest release(s)

### ISSUE THREAD

**Issue by Ghosthree3** [pyroscope/rtorrent-ps#42]
After updating both rtorrent-ps to the latest git build with [https://aur.archlinux.org/packages/rtorrent-pyro-git/](url) and the latest pyrocore update with the update-to-head.sh script attempting to start rtorrent using the default rtorrent-0.8.9.rc for pyro's rc file causes this error on startup.

> rtorrent: Failed to parse command line option: Error in option file: ~/.rtorrent.rc:53: Error in option file: ~/.pyroscope/rtorrent-0.8.9.rc:49: Invalid type.

Which points to this line:

> method.insert = d.last_active, simple|value, "if=$d.peers_connected=,$cat=$system.time=,$d.custom=last_active"

Commenting out the line allows rtorrent-ps to launch, I have experimented within the started client by feeding the line to it with the ^x prompt and the error is the same, Input failed: Invalid type.

Removing |value from the line stops the error (but probably breaks the purpose of the line).

rTorrent-PS git~e291b6e 0.9.6/0.13.6
pyroadmin 0.4.3.dev20161216

**Comment by pyroscope** [comment]
* [ ] Fix to likely just "string"
 * [ ] Add missing details to https://github.com/rakshasa/rtorrent/wiki/Scripting-Guide#variable-types

**Comment by chros73** [comment]
We've been discussed this, there's a [pull request](https://github.com/pyroscope/pyrocore/pull/25/files#diff-9309b47b973e20b5ed08b4c7b61c5b6dR45) for pyrocore project that contains the fix.

**Comment by Ghosthree3** [comment]
I notice the request is for file 0.8.6 only, is it the same for both files? Can I just drop in the new lines to the 0.8.9 one?

**Comment by chros73** [comment]
I think so, but just try it out :)

**Comment by pyroscope** [comment]
The new "rtorrent-pyro.rc" has this fix included.
