### ISSUE TITLE
Build script - Arch Linux support

### ISSUE THREAD

**Issue by xsmile** [pyroscope/rtorrent-ps#48]
Support building packages for Arch Linux. See fork https://github.com/xsmile/rtorrent-ps for changes to the build script.

Things to consider:
- different package naming conventions
- architecture specific  CPPFLAGS, CFLAGS, CXXFLAGS, LDFLAGS, MAKEFLAGS can be sourced from /etc/makepkg.conf
- creating a package: RT_PS_VERSION, RT_PS_REVISION must not contain a hyphen (-)

Attached are a log files for the "install" and "pkg2pacman" operations, in case you want to trace the whole process yourself: [rtorrent-ps-arch.zip](https://github.com/pyroscope/rtorrent-ps/files/829577/rtorrent-ps-arch.zip)

```
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

```
$ gcc --version | head -n1 | tr -s '()' ' ' | cut -f2 -d' '
GCC
```

**Comment by xsmile** [comment]
Additionally I created PKGBUILD scripts for the Arch User Repository (AUR) with plans to maintain them, as currently they run fine here and use less memory.
The build process is different. I adopted the the patching process, the dependencies (curl etc.) however are managed by the OS.

https://aur.archlinux.org/packages/libtorrent-ps/
https://aur.archlinux.org/packages/rtorrent-ps/

**Comment by pyroscope** [comment]
Nicely done. :+1: 

Refactored pacman support coming up, please test after it's pushed.

**Comment by pyroscope** [comment]
:100: % done.
