### ISSUE TITLE
Add throttle and upload amount to main canvas

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/rtorrent-ps#5]
- Add "⊘" or "∅" column and put the 1st letter of the throttle name under it (∞ for NULL, space for NONE)
- Add upload after size (⊼ or ⋏)
- Make the 2nd configurable

**Comment by chros73** [comment]
0. +1

1. Can we add more new fields through the config file? e.g.:
- I want to display 1 more custom field, which could work as for the throttle name
- if we want to display custom fields that store timestamp (like you d.last_active field), which could work as the time field

2. can we configure these custom fields to be visible per view?
- e.g. I only want to display d.downloaded_time on main view
(this one isn't important)

PS: I have compiled a package from version 0.9.5 on ubuntu 14.04 trusty, I can send it over to you via email, and you can upload it to bintray, if you like.
And, again, thank you for the amazing work you've put in in this project!

**Comment by chros73** [comment]
Have you seen my pull request?
I hope you don't mind the included extra information.
If you don't like it at all you can reject it (I want to commit my other changes as well and I don't want to deal with any unnecessary merge issues :) ).
And thanks for your patches! I wouldn't even think about modifying rtorrent with them!

**Comment by pyroscope** [comment]
Just pressed for time, in May there should be some left for this. Remind me in IRC.

**Comment by pyroscope** [comment]
Done in #60
