### ISSUE TITLE
Command: view.query=viewname,condition(s)

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/rtorrent-ps#57]
* Like ``view.filter``, but return a list of hashes instead of changing the view display
* Use a more versatile query language? (SQL like dialect)
* Need at least an operator comparing item attributes against a literal string / a pattern / a regex
* Include optional sorting, and field selection?

**Comment by chros73** [comment]
Good idea!

@toff created a `match` command that is part of his [temp filter](https://github.com/chros73/rtorrent-ps/issues/63) patch that uses regexp.

**Comment by pyroscope** [comment]
implemented as `d.multicall.filtered` in 0b3d5fe
