### ISSUE TITLE
Add 'string.*' command group

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/rtorrent-ps#59]
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#string-functions

* :heavy_check_mark: Update / finish documentation
* :heavy_check_mark: UTF8 support for all this!
* :heavy_check_mark: `string.len` → value
* :heavy_check_mark: `string.substr` → string
* :heavy_check_mark: `string.strip` → string (optional char sequence to strip, lstrip / rstrip?)
* :heavy_check_mark: `string.replace` → string
* :heavy_check_mark: `string.map` → string
* :heavy_check_mark: `string.split` → list
* :heavy_check_mark: `string.join` → string – like `cat`, but with a delimiter
* :heavy_check_mark: `string.contains[_i]` → value
* :heavy_check_mark: `string.equals` → value
* :heavy_check_mark: `string.endswith` → value
* :heavy_check_mark: `string.startswith` → value
* :x: `string.chop` – see ``string.substr``
* :heavy_check_mark:  `string.[lr]pad` → string

**Comment by pyroscope** [comment]
See also 3b9b5e7

**Comment by chros73** [comment]
I create 2 new methods that should work like `math.*` commands (accepting both string and number), what shall I call the group?
`data.*` or `chars.*` or ... ?

- exposing `u8_chop` : `*.chop` (accepts max 2 params)
- `*.pad` (accepts max 4 param)

This group suppose to deal with strings and do some manipulation on them, but it behaves differently than the `string.*` group.
It can be used to display something on the UI or during logging (`log.execute`).

Thanks

**Comment by chros73** [comment]
Here's the [usage examples](https://github.com/chros73/rtorrent-ps-ch_setup/blob/e199fe818d5c253da47197db0ae2833a4a8a9f88/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L157) for the `chars.*` group, I extended your idea of [logging](https://github.com/chros73/rtorrent-ps-ch_setup/issues/142).
Thanks for this as well!

**Comment by pyroscope** [comment]
A string is a list of *chars*, I don't see the need for a new group name. That they implicitly convert values is not enough ‘different’ for me. Things are complicated enough, and adding a stink of PHP doesn't help. ;)

**Comment by chros73** [comment]
:D :D :D You can rename them in ps, and I will rename it in ch if the setup project will reach 1.0 (I want to do couple of nontrivial things until then). That's why I asked for your opinion back then. It matters for me!
