### ISSUE TITLE
Add patches to fix thread names to include rtorrent

### ISSUE THREAD

**Issue by NoSubstitute** [pyroscope/rtorrent-ps#6]
rakshasa patched rt original source to add rtorrent to thread names. Please add them here too.

https://github.com/rakshasa/libtorrent/commit/425d5fde8d2a9e65894eb5e3eaa188362628218f
https://github.com/rakshasa/rtorrent/commit/8e69930cc4cf98f74a63f08e2f9e054756ddd032

**Comment by NoSubstitute** [comment]
Any hope of this being implemented soon?
It looked like fairly simple edits, that shouldn't impact anything else negatively.

**Comment by pyroscope** [comment]
Use 0.9.5.
