### ISSUE TITLE
How many torrents per instance? Is there a safe limit?

### ISSUE THREAD

**Issue by 01100001** [pyroscope/rtorrent-ps#62]
I am currently seeding ~ 1800 torrents, ~ 50 MB average size of each torrent. There are about 15K more that I plan to add and seed indefinitely. I see that I'd need to run multiple instances of rTorrent, but would like to know how many to keep per instance. Is there a safe no. where the reliability of rTorrent isn't affected? (crashing, missing torrent files in watch directory, forgetting where data is, problems bulk hash-checking/rehashing, etc.)

Any advice is appreciated. Thanks!

**PS:** I am thinking ~ 7k per instance, but if known to be safe, doing 10k would be awesome and much less pain.

**Comment by chros73** [comment]
> I see that I'd need to run multiple instances of rTorrent

Why is that?

> where the reliability of rTorrent isn't affected?

I can't say anything in my experience but someone stated [here](https://github.com/rakshasa/rtorrent/issues/180#issuecomment-55140832): 
"seeding over 40,000 torrents with an average size of 4mb. Just goes to show how insanely good this software is that it can handle that kind of load" 

I suggest try all the torrents in 1 client.

**Comment by 01100001** [comment]
> I suggest try all the torrents in 1 client.

👌 Would love to see how this goes.
