### ISSUE TITLE
random_r not available on Alpine Linux (musl C)

### ISSUE THREAD

**Issue by deed02392** [pyroscope/rtorrent-ps#74]
https://github.com/pyroscope/rtorrent-ps/blob/master/patches/command_pyroscope.cc#L78

There is a portability issue with the above file, where glibc is depended on and not available on all Linux distros, namely Alpine Linux where I am hoping to base an rtorrent-ps container on.

Please could a C++ developer take a look at using an alternative random function. musl C does provide a random but I am not sure how suitable it is as a drop in replacement. The systemd project does fall back to it in the following: https://github.com/kraj/meta-musl/blob/master/recipes-core/systemd/systemd/0029-sd-ipv4all-fall-back-to-random-if-no-random_r.patch

**Comment by pyroscope** [comment]
Either use alpine-glibc or minideb. Or even the normal stretch image – size is an optimization, make it work first, THEN optimize.

**Comment by deed02392** [comment]
I have already built a working Stretch based container. So I'm now in the optimisation stage of your mantra. :-) are you concerned there are lots of other portability issues than this one?

**Comment by pyroscope** [comment]
well, try alpine-libc, musl can be a can of worms. it's just another .2 MiB.

**Comment by pyroscope** [comment]
and btw, making PRs of the working stretch setup as an intermediate step expedites things. i don't like big-bang changesets that are hard to review.

**Comment by pyroscope** [comment]
btw #2, I need a configured Stretch environment anyway, to test rt-ps *and* the p-m-b setup on the *common* target platform.

**Comment by deed02392** [comment]
I will try alpine-glibc, that is a good idea.

The working Stretch setup is pretty alpha - you have to go and change the defaults.yml for everything rather than it actually pulling in host_vars because ansible-container doesn't work like that. I am happy to share it with you but I don't think a PR would be hugely clear anyway? Getting the container building really wasn't a lot of effort. Getting it working on Alpine hasn't been much more difficult either - the most complicated thing has been figuring out what deps are called in Alpine repos versus Debian :-)

Let me know if you really want to see my Stretch ansible-container code and if so, how I should best share it with you. I think a new repo would make the most sense, because ansible-container hierarchy is quite different to plain ol' ansible.

**Comment by deed02392** [comment]
@pyroscope Building for alpine-glibc is being a pain. It really would be better if we just got around to making pyroscope compile under musl C.

**Comment by pyroscope** [comment]
stale, and if you want extended platform support, upstream is the right place.
