### ISSUE TITLE
log.messages command is broken

### ISSUE THREAD

**Issue by chros73** [pyroscope/rtorrent-ps#78]
Here's the working [missing patch](https://github.com/chros73/rtorrent-ps-ch/blob/5a06ba940b250c71b92be45ed5b735ac248048d2/patches/ps-log_messages_all.patch) for current master branch.

Refers to:  https://github.com/pyroscope/pimp-my-box/issues/21

**Comment by pyroscope** [comment]
Must've been a collateral of patch house-keeping.
