### ISSUE TITLE
Docs update: How to make PuTTY show all rt-ps glyphs in Windows

### ISSUE THREAD

**Issue by NoSubstitute** [pyroscope/rtorrent-ps#8]
Download and install these two fonts.

<b>EverMono</b>
http://www.evertype.com/emono/
http://www.evertype.com/emono/evermono.zip

<b>DejaVu Sans Mono</b>
http://dejavu-fonts.org/wiki/Download
http://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-fonts-ttf-2.37.zip

Use <b>font linking</b> to make EverMono complement DevaVu Sans Mono.

Add (or Edit) a multi-string value for your preferred font under the Windows registry key

Start <b>Regedit</b>. Go to the key below.

> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink

The added (or edited) key name should be the font name, and the value associated is a list of fallback font options to display the characters not recognized by previous font. There should be some existing ones, you can copy the value from there. Or, add a new Multi String key.

That's what you should do.
Right click <b><i>SystemLink</i></b> and select <b><i>New</i></b>, then <b><i>Multi String Value</i></b>.
Name it <b>DejaVu Sans Mono</b>.

After it's been created, double-click it and enter this inside.
<b>Everson Mono.ttf,EversonMono</b>

At the very least you must logout from Windows and back in again to activate this font link, but I recommend a full reboot.

Now, after rebooting, with PuTTY running change the settings for fonts. Click the PuTTY icon, top-left on your PuTTY window, and then <b><i>Change settings</i></b>. Go to <b><i>Window / Appearance</i></b> and select <b>DejaVu Sans Mono</b>.

<b>Now your rtorrent-PS should look as beautiful as pyroscope always intended it!</b>

Base info taken from 
http://superuser.com/questions/393834/how-to-configure-putty-to-display-these-characters/764855#764855
Complemented with the MSDN doc linked therein.
https://msdn.microsoft.com/en-us/goglobal/bb688134.aspx

**Comment by chros73** [comment]
Wow! Nice job, thanks! 
I'll try it out. My only concern is that the small ratio glyphs.

This is what I'm using now, it's in the same DejaVu set.
You can add as an alternative solution, and it's more simpler:
- use Putty version 0.64b or greater (to be able to have bold fonts)
- under terminal: x "Use background colour to erase screen"
- under colors: set "Indicate bold text by setting: both"
- under appearance: x "allow selection of variable pitch font", Font: DejaVu Sans Condensed, size: 9 .

This DejaVu font was the only one (that I tried) which can display all fonts and text is still readable. Not perfect, but close:
- some glyphs are missing from the header (but it doesn't bother me)
- left side of the fonts can be chopped off from some wider character
- good thing: ratio glyphs are clearly visible

**Comment by NoSubstitute** [comment]
Yeah, I'm not using beta versions of PuTTY. Still on 0.64.
I'm not a big fan of DejaVu Mono in bold. I think it's easier to read text (irssi, mc, pyWA, top) in normal. Consider I use my tmux for four other panes at the same time as rt-ps.
Also, I'm on a 1920x1080p 17" laptop, with PuTTY at 210x65, so with font size 10 I can hardly read (I can't) those ratio glyphs (column 7?). I just want them to be right, and not broken.

The entire point of this exercise is/was to inform how to display <b>all glyphs</> in Windows.
So "simpler" isn't a viable alternative solution, if it doesn't display all glyphs.

**Comment by pyroscope** [comment]
You know the RTFM thing... :smirk:

Ratio (☹ plus color indication for < 1, ➀ — ➉ : >= the number, ⊛ : >= 11); change to a different set of number glyphs using ui.style.ratio.set=2 (or 3), 0 is a mostly ASCII one

**Comment by chros73** [comment]
@NoSubstitute Thanks for this great idea, it's working pretty well! :) (I haven't known that such a fallback exist.)
"So "simpler" isn't a viable alternative solution, if it doesn't display all glyphs." : Yes, you're right.
I still prefer DejaVu Sans Condensed font over the Mono one: the special characters are much bigger with it (font size: 9, fullHD resolution, 15"4 screen size). So I did your font linking with this font (all chars are good now in the header). Here's the required registry entry: save it as dejavucondensed-eversonmono-link.reg , and run it.
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink]
"DejaVu Sans Condensed"=hex(7):45,00,76,00,65,00,72,00,73,00,6f,00,6e,00,20,00,4d,\
  00,6f,00,6e,00,6f,00,2e,00,74,00,74,00,66,00,2c,00,45,00,76,00,65,00,72,00,\
  73,00,6f,00,6e,00,4d,00,6f,00,6e,00,6f,00,00,00,00,00
```
What kind of OS and OS version and rtorrent-ps version do you use? I'm asking because of this: 
https://groups.google.com/forum/#!topic/pyroscope-users/_5yMqjIHcpo
(You can answer there.)

@pyroscope "ui.style.ratio.set=2" Thanks I haven't know that either :) I tried them out, but I like the default (1) icons with this font.
