### ISSUE TITLE
Segfault with torrent removal

### ISSUE THREAD

**Issue by JRWR** [pyroscope/rtorrent-ps#80]
```
Caught Segmentation fault, dumping stack:
/opt/rtorrent/bin/rtorrent() [0x4136c2]
/opt/rtorrent/bin/rtorrent() [0x45327a]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f906a091f20][0x1ce4a60]
Aborted (core dumped)
```
Its pretty consistent, and happens all the time, It is happening at random times but I have noticed it tends to be linked to torrent deletion over SCGI (rtcontrol) under high loads (about 1500 torrents) and 120% System Load

Using the prebuilt packages for Debian -- rTorrent PS-1.0-104-g07be19e 0.9.6/0.13.6
Linux ovh 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

My .rtorrent.rc

```
scgi_port = 127.0.0.1:5000
port_range = 33101-33199
ratio.enable=
ratio.min.set=400
ratio.max.set=2000
schedule = low_diskspace,5,60,close_low_diskspace=2000M
session = /home/rtorrent/.rtorrent
directory = /home/rtorrent/leeching
max_downloads_global = 300
max_uploads = 1000
min_peers = 1
max_peers = 500
max_uploads_global = 20000
port_random = yes
encryption = allow_incoming,try_outgoing,enable_retry,prefer_plaintext
network.xmlrpc.size_limit.set = 16M
system.file_allocate.set = no
scheduler.max_active.set=20
system.method.set_key=event.download.closed,on_close,"scheduler.simple.update="
system.method.set_key=event.download.paused,on_pause,"scheduler.simple.update="

method.set_key = event.download.erased, remove_file,"execute={rm,-drf,--,$d.get_base_path=}"
system.method.set_key = event.download.finished, extract-finished, "execute = /bin/bash, /home/rtorrent/scripts/extract.sh, $d.get_base_path="
```
Just turned on debug logging, Ill update when I get another crash

**Comment by pyroscope** [comment]
dusable that buggy internal scheduler – why do you even have those lines?

Also, get decided who deletes data – i.e. remove that event.download.erased handler, and use --cull.

**Comment by JRWR** [comment]
event.download.erased handler is handy when on top of it you do rar extraction in place, unless cull will cleanup what ever else was in the folder

**Comment by pyroscope** [comment]
1. Remove the `scheduler.max_active.set=20`
2. With your events, use `--delete``, not `--cull`

If this then still happens, reopen (though then it is still likely an upstream problem).
