### ISSUE TITLE
Support for Ubuntu Bionic

### ISSUE THREAD

**Issue by Gerald6494** [pyroscope/rtorrent-ps#81]
Hello I'm using **ansible** to run **pimp-my box** for the target server **ubuntu 18.04 Bionic**, I'm getting the error below. I hope you can help me fix this Thanks.

remote@DESKTOP-SGFJC4U:~/src/pimp-my-box$ sudo ansible-playbook -i hosts site.yml -v
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead. This feature will be
removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo'
(default). This feature will be removed in version 2.6. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

PLAY [box] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [my-box]

TASK [common : Update APT cache] ***************************************************************************************
changed: [my-box] => {"cache_update_time": 1525635970, "cache_updated": true, "changed": true}

TASK [common : Install basic tools] ************************************************************************************
ok: [my-box] => (item=[u'autossh', u'bash-completion', u'bc', u'bind9-host', u'bzip2', u'cfv', u'colordiff', u'coreutils', u'curl', u'gawk', u'genisoimage', u'git', u'haveged', u'htop', u'httpie', u'inxi', u'iotop', u'lftp', u'links', u'lnav', u'lsb-release', u'lsof', u'mailutils', u'mediainfo', u'mkvtoolnix', u'ncdu', u'p7zip-full', u'psmisc', u'python-virtualenv', u'sysstat', u'tmux', u'unzip', u'vim', u'virtualenvwrapper', u'vnstat', u'wget', u'zip']) => {"cache_update_time": 1525635970, "cache_updated": false, "changed": false, "item": ["autossh", "bash-completion", "bc", "bind9-host", "bzip2", "cfv", "colordiff", "coreutils", "curl", "gawk", "genisoimage", "git", "haveged", "htop", "httpie", "inxi", "iotop", "lftp", "links", "lnav", "lsb-release", "lsof", "mailutils", "mediainfo", "mkvtoolnix", "ncdu", "p7zip-full", "psmisc", "python-virtualenv", "sysstat", "tmux", "unzip", "vim", "virtualenvwrapper", "vnstat", "wget", "zip"]}

TASK [common : Install ffmpeg] *****************************************************************************************
**skipping: [my-box] => {"changed": false, "skip_reason": "Conditional result was False"}**

TASK [common : Install libav] ******************************************************************************************
**fatal: [my-box]: FAILED! => {"changed": false, "msg": "No package matching 'libav-tools' is available"}**
        to retry, use: --limit @/home/remote/src/pimp-my-box/site.retry

PLAY RECAP *************************************************************************************************************
my-box                     : ok=3    changed=1    unreachable=0    failed=1

**Comment by pyroscope** [comment]
Wrong project. 

https://github.com/pyroscope/pimp-my-box/issues/25
